  1 .PHONY:all
  2 all:set -lcurses
  3 
  4 set:set.c
  5         gcc -o $@ $^ -lcurses 
  6 
  7 .PHONY:clean
  8 clean:all
  9         rm -f set 
~                                                                         
~                        
